# Урок 02. Матрицы и линейные преобразования

> **Зачем это нужно:** один слой нейросети — это умножение матрицы на вектор плюс смещение.

---

## 1. Матрица — это таблица чисел

Матрица размера m × n — это таблица из m строк и n столбцов.

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


В ML почти всё — матрицы. Датасет: строки — объекты, столбцы — признаки. Веса слоя: строки — выходные нейроны, столбцы — входные.


## 2. Транспонирование

Транспонирование меняет строки и столбцы местами: `A.T[i, j] = A[j, i]`.

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.T)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


## Свойства операции транспонирования матриц

**Транспонирование** (обозначается как $A^T$) — это операция, при которой строки матрицы становятся столбцами, а столбцы — строками. 

---

### Математические свойства

1. **Двойное транспонирование (Инволюция)**
   Если транспонировать матрицу дважды, она вернется к своему исходному состоянию:
$$ (A^T)^T = A $$

2. **Транспонирование суммы**
   Транспонированная сумма двух матриц равна сумме их транспонированных копий (операция дистрибутивна относительно сложения):
$$ (A + B)^T = A^T + B^T $$

3. **Умножение на скаляр (число)**
   Константу $\alpha$ можно свободно выносить за знак транспонирования:
$$ (\alpha A)^T = \alpha A^T $$

4. **Транспонирование произведения (Важнейшее свойство!)**
   При транспонировании произведения матриц их порядок меняется на **противоположный**:
$$ (A B)^T = B^T A^T $$
   *Для произведения трех матриц:* 
$$ (A B C)^T = C^T B^T A^T $$

5. **Связь с обратной матрицей**
   Операции взятия обратной матрицы ($A^{-1}$) и транспонирования можно менять местами:
$$ (A^{-1})^T = (A^T)^{-1} $$

6. **Определитель матрицы (Детерминант)**
   Определитель матрицы при транспонировании не изменяется:
$$ \det(A) = \det(A^T) $$

---

### Особые типы матриц

* **Симметричная матрица**: Матрица, для которой транспонирование ничего не меняет:
$$ A^T = A $$

* **Кососимметричная матрица**: Матрица, у которой при транспонировании меняется знак всех элементов:
$$ A^T = -A $$

* **Ортогональная матрица**: Квадратная матрица, у которой транспонированная версия совпадает с обратной матрицей:
$$ A^T = A^{-1} \implies A^T A = A A^T = I $$
   *(где $I$ — единичная матрица)*


In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# Поэлементное умножение
print(A * B)

# Матричное умножение
print(A @ B)

alpha = 5.5

print("Матрица A:\n", A)
print("\nМатрица B:\n", B)
print("-" * 50)

# --- ПРОВЕРКА СВОЙСТВ ---

# Свойство 1: Двойное транспонирование ((A^T)^T = A)
property_1_left = (A.T).T
p1_match = np.allclose(property_1_left, A)
print(f"1. Двойное транспонирование совпадает: {p1_match}")

# Свойство 2: Транспонирование суммы ((A + B)^T = A^T + B^T)
property_2_left = (A + B).T
property_2_right = A.T + B.T
p2_match = np.allclose(property_2_left, property_2_right)
print(f"2. Транспонирование суммы совпадает: {p2_match}")

# Свойство 3: Умножение на скаляр ((alpha * A)^T = alpha * A^T)
property_3_left = (alpha * A).T
property_3_right = alpha * (A.T)
p3_match = np.allclose(property_3_left, property_3_right)
print(f"3. Умножение на скаляр совпадает: {p3_match}")

# Свойство 4: Транспонирование произведения ((A @ B)^T = B^T @ A^T)
# ВАЖНО: используем оператор @ для матричного умножения
property_4_left = (A @ B).T
property_4_right = B.T @ A.T
p4_match = np.allclose(property_4_left, property_4_right)
print(f"4. Транспонирование произведения совпадает: {p4_match}")

# Свойство 5: Связь с обратной матрицей ((A^-1)^T = (A^T)^-1)
# Сначала находим обратную матрицу через np.linalg.inv
A_inv = np.linalg.inv(A)
property_5_left = (A_inv).T
property_5_right = np.linalg.inv(A.T)
p5_match = np.allclose(property_5_left, property_5_right)
print(f"5. Связь с обратной матрицей совпадает: {p5_match}")

# Свойство 6: Определитель матрицы (det(A) == det(A^T))
# Считаем определитель через np.linalg.det
det_A = np.linalg.det(A)
det_A_T = np.linalg.det(A.T)
p6_match = np.isclose(det_A, det_A_T) # np.isclose используется для одиночных чисел
print(f"6. Определители равны: {p6_match}")


[[2 0]
 [3 8]]
[[ 4  4]
 [10  8]]
Матрица A:
 [[1 2]
 [3 4]]

Матрица B:
 [[2 0]
 [1 2]]
--------------------------------------------------
1. Двойное транспонирование совпадает: True
2. Транспонирование суммы совпадает: True
3. Умножение на скаляр совпадает: True
4. Транспонирование произведения совпадает: True
5. Связь с обратной матрицей совпадает: True
6. Определители равны: True


## 3. Умножение матрицы на вектор

Это **главная операция в нейросетях**.

$$ y = A x, \quad y_i = \sum_{j} A_{ij} x_j $$

Геометрически: `A @ x` — это применение линейного преобразования `A` к точке `x`.

In [6]:
A = np.array([[2, 0], 
              [0, 3]])

x = np.array([1, 1])

print(A @ x) # [2 3] — растяжение в 2 раза по X, в 3 раза по Y


[2 3]


Поворот на угол θ:

In [7]:
theta = np.pi / 4
R = np.array([[np.cos(theta), -np.sin(theta)],
             [np.sin(theta), np.cos(theta)]])

x = np.array([1, 0])
print(R @ x) # [0.707, 0.707] — повернули на 45°

[0.70710678 0.70710678]


## 4. Умножение матриц

$$ (AB)_{ij} = \sum_{k} A_{ik} B_{kj} $$

Размеры: `(m × n) @ (n × p) = (m × p)`. Внутренние размеры должны совпадать.

In [8]:
rng = np.random.default_rng(seed=42)

A = np.random.randn(3, 4) # устаревший способ создания матрицы 3 на 4
B = rng.normal(size=(4, 3)) # новый способ
C = A @ B
print(C)
print(C.shape)


[[ 0.03543749  0.39095821  0.31818602]
 [-1.26047077  1.53703282  0.64026076]
 [ 1.3957385  -2.54576543 -2.07863384]]
(3, 3)


**Ключевая интуиция:** `AB` — это композиция преобразований. Сначала применили `B`, потом `A`. Поэтому `AB ≠ BA` в общем случае.


## 5. Единичная и обратная матрицы

**Единичная матрица** `I` — единицы на диагонали, нули вне. Для любой матрицы `A·I = I·A = A`.


# 1. Единичная матрица (Identity Matrix)

**Единичная матрица** (обозначается как $I$ или $E$) — это квадратная матрица, у которой на главной диагонали стоят единицы, а все остальные элементы равны нулю. В матричном анализе она играет роль обычной «единицы» из арифметики.

### Математический вид (размер 3 × 3)
$$I = \left( \begin{matrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{matrix} \right)$$

### 📋 Свойства единичной матрицы
* **Нейтральность при умножении:** Умножение любой матрицы $A$ на единичную матрицу $I$ (подходящего размера) оставляет её неизменной. Порядок умножения здесь не важен:
$$A \cdot I = I \cdot A = A$$
* **Транспонирование:** Операция транспонирования никак не изменяет единичную матрицу:
$$I^T = I$$

---

# 2. Обратная матрица (Inverse Matrix)

**Обратная матрица** для квадратной матрицы $A$ (обозначается как $A^{-1}$) — это такая матрица, умножение на которую дает единичную матрицу $I$. Она заменяет операцию деления, которой для матриц не существует.

### Математическое определение
$$A \cdot A^{-1} = A^{-1} \cdot A = I$$

###  Условия существования
Обратная матрица существует **только** если выполняются два условия:
1. Матрица является строго **квадратной**.
2. Её определитель (детерминант) **не равен нулю**:
$$\det(A) \neq 0$$
*(Если $\det(A) = 0$, матрица называется вырожденной или сингулярной. Найти обратную для неё невозможно).*

### 📋 Свойства обратной матрицы
* **Обратная к обратной:** Двойное взятие обратной матрицы возвращает исходную:
$$(A^{-1})^{-1} = A$$
* **Обратная от произведения:** При инверсии произведения матриц их порядок меняется на противоположный:
$$(A \cdot B)^{-1} = B^{-1} \cdot A^{-1}$$
* **Взаимосвязь с транспонированием:** Операции транспонирования и взятия обратной матрицы можно менять местами:
$$(A^T)^{-1} = (A^{-1})^T$$


In [9]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
A = np.array([[1, 2],
              [3,4]])
A_inv = np.linalg.inv(A)

print(A_inv)
print(A @ A_inv)
print(A_inv @ A)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


В реальном коде **никогда не считайте `inv(A)` для решения систем** — используйте `np.linalg.solve(A, b)`. Это быстрее и численно устойчивее.


In [11]:
A = np.array([[1, 2],
              [3,4]])
I = np.eye(2)
A_inv = np.linalg.solve(A, I)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


## 6. Линейная регрессия за 3 строки

### Обратная матрица в Линейной Регрессии

В машинном обучении обратная матрица используется для **прямого аналитического расчета оптимальных весов** ($w$) модели через метод наименьших квадратов (МНК).

###  Формула нормального уравнения
Чтобы найти веса за один шаг, применяется матричное уравнение:
$$w = (X^T X)^{-1} X^T y$$

* $X$ — матрица признаков (*объекты $\times$ признаки*).
* $X^T X$ — квадратная матрица (*признаки $\times$ признаки*).
* $(X^T X)^{-1}$ — **обратная матрица**, которая заменяет операцию деления (в матричном анализе деления не существует).

---

###   Главная проблема: Мультиколлинеарность
Обратная матрица существует только тогда, когда $\det(X^T X) \neq 0$. 

Если в данных есть **сильно зависимые признаки** (например, рост в см и рост в метрах):
* Столбцы матрицы $X$ становятся линейно зависимыми.
* Определитель $\det(X^T X)$ падает до нуля.
* Матрица становится вырожденной, и код выдает ошибку `Singular matrix`.

**Решение в ML:** Использование **Ridge (L2) регуляризации**. К матрице прибавляют единичную матрицу $\alpha I$, искусственно уводя определитель от нуля: $(X^T X + \alpha I)^{-1}$.

---

###  Почему её редко используют на больших данных?
1. **Высокая сложность:** Вычислительная сложность инверсии матрицы составляет $O(N^3)$, где $N$ — количество признаков. При 100 000 признаков компьютер зависнет.
2. **Альтернатива:** На больших датасетах и в нейросетях вместо обратной матрицы используют **Градиентный спуск (Gradient Descent)**, который ищет веса итеративно.




## Математика кода: Решение нормального уравнения

Код моделирует процесс линейной регрессии $y = Xw + \epsilon$ и находит оптимальные веса $w$ аналитически через **Метод Наименьших Квадратов (МНК)**.

### 1. Вывод уравнений (Минимизация ошибки)
Мы ищем вектор весов $w$, который минимизирует функционал среднеквадратичной ошибки (MSE):
$$L(w) = \|Xw - y\|^2 = (Xw - y)^T(Xw - y)$$

После раскрытия скобок и группировки слагаемых получаем:
$$L(w) = w^T X^T X w - 2w^T X^T y + y^T y$$

Чтобы найти минимум, берем матричную производную (градиент) по вектору $w$ и приравниваем её к нулю:
$$\frac{\partial L}{\partial w} = 2X^T X w - 2X^T y = 0$$

Сокращаем на 2 и получаем фундаментальную **систему нормальных уравнений**:
$$X^T X w = X^T y$$

---

### 2. Математика `np.linalg.solve` против `np.linalg.inv`

Вместо явного поиска обратной матрицы $(X^T X)^{-1}$, строка `np.linalg.solve(X.T @ X, X.T @ y)` решает стандартную систему линейных уравнений (СЛАУ) вида $Aw = b$, где:
* $A = X^T X$ — квадратная матрица (*признаки $\times$ признаки*) размера $5 \times 5$.
* $b = X^T y$ — вектор свободных членов длины $5$.

| Критерий | Явное обращение `inv()`: $w = A^{-1}b$ | Решение через `solve(A, b)` |
| :--- | :--- | :--- |
| **Алгоритм** | Сначала ищет матрицу $A^{-1}$, затем умножает на $b$. | Находит $w$ напрямую через **LU-разложение** (метод Гаусса). |
| **Точность** | Теряет точность из-за накопления погрешностей `float`. | **Максимальная**, так как нет промежуточного деления на $\det(A)$. |
| **Скорость** | Медленнее, требует больше вычислительных ресурсов. | **Быстрее**, стандарт индустрии для решения СЛАУ. |

Поэтому вычисленный вектор `w_hat` получается максимально приближенным к `true_w` (с поправкой на случайный шум `0.1 * np.random.randn`).


In [12]:
rng = np.random.default_rng(seed=42)

X = rng.normal(size=(100, 5))
true_w = np.array([1, -2, 3, 0.5, -1])
y = X @ true_w + 0.1 * rng.standard_normal(100)

w_hat = np.linalg.solve(X.T @ X, X.T @ y)
print(w_hat)

[ 0.99214741 -2.00511143  2.99356709  0.49394564 -0.99284279]


## 7. Ранг и вырожденность матриц

Эти два понятия из линейной алгебры определяют, содержит ли таблица данных уникальную информацию и можно ли математически рассчитать веса для аналитических моделей (таких как МНК).

---

### 1. Ранг матрицы (Rank)

**Ранг матрицы** $\text{rank}(A)$ — это максимальное количество **линейно независимых** строк или столбцов в матрице. 

* **Линейная независимость:** строку (или столбец) невозможно получить с помощью линейной комбинации (складывания или умножения на числа) других строк.
* **Смысл в ML:** ранг показывает объем *реальной, уникальной информации* в датасете.
* **Полноранговая матрица (Full Rank):** матрица размера $M \times N$, у которой ранг равен максимально возможному: $\min(M, N)$. В ней нет скрытых дубликатов.

> **Пример «на пальцах»:** Если в вашей таблице признаков первый столбец — это «рост в сантиметрах», а второй — «рост в метрах», то второй столбец линейно зависим от первого ($X_2 = X_1 / 100$). Уникальной информации он не несет, поэтому ранг такой матрицы из двух столбцов будет равен всего **1**.

---

### 2. Вырожденность матрицы (Singular Matrix)

**Вырожденная (или сингулярная) матрица** — это квадратная матрица, строки или столбцы которой линейно зависимы. 

Математически вырожденность означает три взаимосвязанных факта:

1. Её определитель (детерминант) строго равен нулю: 
$$\det(A) = 0$$

2. Её ранг меньше её физического размера:
$$\text{rank}(A) < N$$
Матрица потеряла полный ранг.

3. Для неё **не существует обратной матрицы** $A^{-1}$. Попытка её инвертировать эквивалентна делению на ноль.

---

###  Связь с линейной регрессией (МНК)

В методе наименьших квадратов веса находятся из уравнения:
$$(X^T X) \cdot w = X^T y$$

Матрица $A = X^T X$ имеет размер $N \times N$ (где $N$ — количество признаков). Чтобы код `np.linalg.solve(A, b)` или `np.linalg.inv(A)` сработал, матрица $A$ **обязательно должна быть невырожденной**.

Если в данных присутствует **мультиколлинеарность** (сильно зависимые признаки):
1. Матрица признаков $X$ теряет полный ранг.
2. Квадратная матрица $X^T X$ автоматически становится **вырожденной** ($\det(X^T X) = 0$).
3. Программа падает с ошибкой `LinAlgError: Singular matrix`, так как веса невозможно вычислить аналитически.


In [13]:
A = np.array([[1, 2], [2, 4]])
print(np.linalg.matrix_rank(A))

1


## 8. Практические задания

1. **Своё matmul.** Реализуйте умножение матриц без `@` и `np.dot`, через три вложенных цикла. Сравните скорость с NumPy на матрицах 200×200.


In [14]:
import time


rng = np.random.default_rng(seed=42)

A = rng.uniform(-10, 10, size=(200, 200))
B = rng.uniform(-10, 10, size=(200, 200))

C = np.zeros((A.shape[0], B.shape[1]))

start_time_numpy = time.time()
C_numpy = A @ B
end_time_numpy = time.time()


start_time_numpy_no = time.time()
for k in range(A.shape[0]):
    for i in range(B.shape[1]):
        current_sum = 0
        for j in range(A.shape[1]): # B.shape[0]
            current_sum += A[k][j] * B[j][i]
        C[k][i] = current_sum
end_time_numpy_no = time.time()


print(f"Матрицы равны? -> {np.allclose(C_numpy, C)}\n")

execution_time_numpy = end_time_numpy - start_time_numpy
execution_time_numpy_no = end_time_numpy_no - start_time_numpy_no

print(f"Время работы Numpy: {execution_time_numpy}")
print(f"Время работы циклов: {execution_time_numpy_no}")


Матрицы равны? -> True

Время работы Numpy: 0.008439064025878906
Время работы циклов: 3.3759708404541016


2. **Векторизация.** Перепишите своё matmul через NumPy broadcasting без явных циклов. Сколько раз быстрее?


###  Краткая справка: NumPy Broadcasting (Трансляция)

**Broadcasting** — это механизм NumPy, позволяющий выполнять арифметические операции над массивами разной формы (shape) без явных циклов и лишнего копирования данных в памяти.

#### Главное правило совместимости
NumPy сравнивает размеры осей массивов **справа налево**. Две оси совместимы, если:
1. Их размеры **равны**.
2. Разрешение конфликта: один из размеров **равен 1**. Эта ось виртуально растягивается до размера большей.

Если у одного из массивов меньше осей, к его форме слева автоматически дописываются единицы `1`.

---

#### Примеры шаблонов расширения осей

* `(200, 200)` + `()` (скаляр) → Скаляр применяется к каждому элементу матрицы → **`(200, 200)`**
* `(200, 200)` + `(200,)` → Вектор дополняется слева до `(1, 200)` и дублируется по строкам → **`(200, 200)`**
* `(200, 1)` + `(1, 200)` → `A` растягивается вширь, `B` — вниз (образуется сетка) → **`(200, 200)`**
* `(M, N, 1)` + `(1, N, K)` → Обе матрицы дублируются по своим единичным осям → **`(M, N, K)`**

---

#### Универсальное матричное умножение через Broadcasting

Вместо медленных вложенных циклов Python операция умножения матриц:

$$
C_{ki} = \sum_{j} A_{kj} \cdot B_{ji}
$$


векторизуется для любых размерностей (M, N) и (N, K) в три шага:

```python
# 1. Добавляем новые оси, чтобы совместить нужные индексы
A_exp = A[:, :, np.newaxis]  # Форма: (M, N, 1) -> Индексы: (k, j, 1)
B_exp = B[np.newaxis, :, :]  # Форма: (1, N, K) -> Индексы: (1, j, i)

# 2. Поэлементное умножение с автоматическим бродкастингом до (M, N, K)
prod = A_exp * B_exp

# 3. Схлопывание (суммирование) по общей оси N (индекс оси = 1)
C_broadcast = np.sum(prod, axis=1)  # Итоговая форма: (M, K)
```

 **На заметку:** Метод `*` + `np.sum` работает в **~100+ раз быстрее** циклов, но для чистого умножения матриц всегда используйте встроенный оператор `@` (`np.matmul`). Он оптимизирован на уровне C/BLAS и не создает огромный промежуточный 3D-массив в оперативной памяти.


In [15]:
M, N, K = 150, 200, 300
A = np.random.rand(M, N)
B = np.random.rand(N, K)

# Добавляем оси для бродкастинга
# Форма A: (M, N) -> (M, N, 1)
# Форма B: (N, K) -> (1, N, K)
A_expanded = A[:, :, None]  # или A[:, :, np.newaxis]
B_expanded = B[None, :, :]  # или B[np.newaxis, :, :]

# Поэлементное умножение (обе матрицы расширяются до формы (M, N, K))

prod = A_expanded * B_expanded

# Суммируем по общей оси N (индекс j) (в 3D-тензоре это ось с индексом 1)
C_broadcast = np.sum(prod, axis=1)

# Проверка корректности
print("Форма матрицы C:", C_broadcast.shape) # Выведет: (150, 300)
print("Результат совпадает с Numpy?:", np.allclose(C_broadcast, A @ B))


Форма матрицы C: (150, 300)
Результат совпадает с Numpy?: True


### 🔧 Шпаргалка: Что такое np.newaxis (или None)

`np.newaxis` добавляет виртуальную ось размером `1` в форму массива. Это нужно, чтобы подгонять размеры массивов друг под друга для **broadcasting**.

Пусть `x` — массив с формой `(3,)`.

* **`x[np.newaxis, :]`** или **`x[None, :]`** 
  → Превращает в **вектор-строку** с формой `(1, 3)`.
* **`x[:, np.newaxis]`** или **`x[:, None]`** 
  → Превращает в **вектор-столбец** с формой `(3, 1)`.

#### В трехмерных массивах (как в нашей задаче):
* Из `(200, 200)` делаем `(200, 200, 1)` → **`A[:, :, np.newaxis]`** (добавили ось в конец).
* Из `(200, 200)` делаем `(1, 200, 200)` → **`B[np.newaxis, :, :]`** (добавили ось в начало).


---
3. **Поворот картинки.** Загрузите изображение, представьте каждый пиксель как точку (x, y), примените матрицу поворота на 30°. Сохраните результат.


### 💻 Что такое изображение на языке программирования?

С точки зрения кода, любое цветное изображение (например, JPEG) — это **трехмерный массив (тензор) типа данных `uint8`**.

Его структура описывается формой (shape):
$$(\text{Высота}, \text{Ширина}, \text{Каналы})$$

* **Высота и Ширина** задают дискретную сетку координат пикселей.
* **Каналы (обычно 3 для RGB)** хранят интенсивность базовых цветов в диапазоне от 0 (цвет выключен) до 255 (максимальная яркость).

#### Пример в NumPy:
Пиксель на пересечении 5-й строки и 10-го столбца:
```python
pixel = img_array[4, 9]  # Вернет массив из 3-х чисел, например: [120, 255, 40]
# 120 - доля Красного (R), 255 - доля Зелёного (G), 40 - доля Синего (B)
```
Любые фильтры, фотоэффекты и алгоритмы компьютерного зрения — это просто **математические операции над этими матрицами** (умножение, сложение, бродкастинг).


       ┌────────────────────────┐
      /  Red (Красный)         /│
     ├────────────────────────┤ │
    /  Green (Зелёный)       /│ │  C (Каналы = 3)
   ├────────────────────────┤ │ │
  /  Blue (Синий)          /│ │ │
 ┌────────────────────────┐ │ │─┘
 │                        │ │─┘
 │                        │ │      H (Высота — строки пикселей)
 │      П И КС Е Л И      │/
 └────────────────────────┘
 └────────────────────────┘
        W (Ширина — столбцы пикселей)


В обычной школьной математике ось \(Y\) направлена вверх, поэтому положительный поворот идет против часовой стрелки.Но на экране компьютера (в матрицах) ось \(Y\) направлена вниз (строки с номерами 0, 1, 2... идут сверху вниз). Из-за того, что вертикальная ось «перевернута», направление вращения тоже меняется на противоположное.

## Шпаргалка: Афинные преобразования изображений в NumPy

При обработке изображений и матричных трансформациях (поворот, масштабирование) важно помнить специфику компьютерных осей и правила работы с размерностями в Python.

---

### 1. Компьютерные координаты экрана
* **Начало координат $(0, 0)$:** Находится строго в **левом верхнем углу**.
* **Направление осей:** Ось $X$ направлена вправо, ось $Y$ — **вниз**.
* **Сдвиг осей в центр:** Чтобы перенести начало координат в центр изображения $(c_x, c_y)$ **без смены направления осей**, из пиксельных индексов вычитается центр:
  $$X_{centered} = X_{grid} - c_x$$
  $$Y_{centered} = Y_{grid} - c_y$$

---

### 2. Строчный формат данных и матричное умножение `@`
В линейной алгебре формулы пишутся для векторов-столбцов, где матрица трансформации стоит слева: $v_{new} = R \cdot v$. 

В NumPy координаты огромного массива пикселей всегда хранятся в виде **матрицы строк** формы $(N, 2)$, где каждая строка — это отдельная точка $(x, y)$:

$$\text{coords} = \begin{pmatrix} x_1 & y_1 \\ x_2 & y_2 \\ \vdots & \vdots \end{pmatrix}$$

Из-за правила умножения матриц (строка на столбец), порядок вычислений меняется:
1. **Порядок аргументов:** Массив координат ставится на первое место: `coords @ Матрица`.
2. **Транспонирование:** Матрицу трансформации необходимо транспонировать (`.T`), чтобы математически компенсировать смену порядка умножения.

$$\text{old\_coords} = \text{new\_coords} \times R^{T}$$

---

### 3. Обратный метод поворота (Inverse Mapping)
При деформации картинок всегда идут **от пустых пикселей нового изображения к пикселям исходного**:
* Прямой поворот (из старой в новую) оставляет «дырки» и артефакты из-за округления координат.
* Обратный поворот гарантирует, что каждый пиксель новой картинки получит свой цвет. 

Для поворота по часовой стрелке на угол $\alpha$ в обратном методе используется матрица поворота на отрицательный угол $-\alpha$:

$$R_{inverse} = \begin{pmatrix} \cos\alpha & \sin\alpha \\ -\sin\alpha & \cos\alpha \end{pmatrix}$$


In [16]:
from PIL import Image

# 1. Загружаем изображение
img = Image.open("02-matrices-task3-1.jpg")
img_array = np.array(img)
H, W, C = img_array.shape

# 2. Задаем угол и матрицу ПРЯМОГО поворота на 30 градусов по ЧАСОВОЙ стрелке
angle = np.radians(30)
cos_a, sin_a = np.cos(angle), np.sin(angle)

# Считаем размеры новой картинки, чтобы углы не обрезались
new_W = int(abs(W * cos_a) + abs(H * sin_a))
new_H = int(abs(W * sin_a) + abs(H * cos_a))

# Находим центры старого и нового изображений 
# (чтобы вращать вокруг центра, а не вокргу верхнего 
# левого угла)
cx, cy = W / 2.0, H / 2.0
new_cx, new_cy = new_W / 2.0, new_H / 2.0

# 3. Генерируем сетку координат (X, Y) для НОВОЙ (пустой) картинки
x_range = np.arange(new_W)
y_range = np.arange(new_H)
X_grid, Y_grid = np.meshgrid(x_range, y_range)

# Сдвигаем координаты новой сетки так, чтобы центр стал точкой (0, 0)
x_flat = X_grid.ravel() - new_cx
y_flat = Y_grid.ravel() - new_cy
new_coords = np.column_stack((x_flat, y_flat))  # Форма: (new_H * new_W, 2)

# 4. Задаем матрицу ОБРАТНОГО поворота (на -30 градусов) для возврата к старой картинке
# Матрица поворота: [[cos, -sin], [sin, cos]]. Для -30 градусов синус меняет знак.
R_inverse = np.array([
    [cos_a, sin_a],
    [-sin_a, cos_a]
])

# Вращаем новые координаты "назад" с помощью матричного умножения @
# В ней для каждого пикселя новой картинки записано, 
# из какого места старой картинки нужно взять цвет.
old_coords = new_coords @ R_inverse.T

# Возвращаем центр старой картинки на место
old_coords[:, 0] += cx
old_coords[:, 1] += cy

# 5. Округляем полученные координаты до ближайших целых индексов пикселей
old_x = np.round(old_coords[:, 0]).astype(int)
old_y = np.round(old_coords[:, 1]).astype(int)

# 6. Маска бродкастинга: находим только те точки, которые попали внутрь старой картинки
inside_mask = (old_x >= 0) & (old_x < W) & (old_y >= 0) & (old_y < H)

# Создаем пустой черный массив для новой картинки
rotated_array = np.zeros((new_H, new_W, C), dtype=np.uint8)

# Переносим цвета из старой картинки в новую по вычисленным индексам
# Делаем это плоскими лентами, используя маску
rotated_array.reshape(-1, C)[inside_mask] = img_array[old_x[inside_mask], old_y[inside_mask]]

# 7. Сохраняем результат
result_img = Image.fromarray(rotated_array)
result_img.save("rotated_30.jpg")
print(f"Изображение успешно повернуто и сохранено! Новая форма: {rotated_array.shape}")


Изображение успешно повернуто и сохранено! Новая форма: (836, 836, 3)


4. **Линейная регрессия с нуля.** На датасете Boston Housing решите `X^T X w = X^T y`. Сравните MSE с `sklearn.LinearRegression`.


$$Y = Xw + \varepsilon$$

Где структура матриц выглядит следующим образом:

$$\begin{pmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{pmatrix} = \begin{pmatrix} 1 & x_{11} & x_{12} & \dots & x_{1k} \\ 1 & x_{21} & x_{22} & \dots & x_{2k} \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 1 & x_{n1} & x_{n2} & \dots & x_{nk} \end{pmatrix} \begin{pmatrix} w_0 \\ w_1 \\ w_2 \\ \vdots \\ w_k \end{pmatrix} + \begin{pmatrix} \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_n \end{pmatrix}$$
$$w = (X^T X)^{-1} X^T Y$$


In [17]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error 
from sklearn.model_selection import train_test_split

column_names = [
    "CRIM",
    "ZN",
    "INDUS",
    "CHAS",
    "NOX",
    "RM",
    "AGE",
    "DIS",
    "RAD",
    "TAX",
    "PTRATIO",
    "B",
    "LSTAT",
    "MEDV",
]
data = pd.read_csv(
    "boston_housing.csv", header=None, delimiter=r"\s+", names=column_names
)

X_matrix = data.drop(columns=["MEDV"]).values
y_vector = data["MEDV"].values

# 1. Разделяем исходные данные на train/test ДО добавления единиц
X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X_matrix, y_vector, test_size=0.3, random_state=42
)

# ВАРИАНТ 1: РУЧНОЙ МАТРИЧНЫЙ РАСЧЕТ
# Добавляем единичный столбец к обучающей и тестовой выборкам
X_train_manual = np.hstack([np.ones((X_train_raw.shape[0], 1)), X_train_raw])
X_test_manual = np.hstack([np.ones((X_test_raw.shape[0], 1)), X_test_raw])

# Считаем веса w строго по обучающей выборке
X_transpose = X_train_manual.T
w = np.linalg.inv(X_transpose @ X_train_manual) @ X_transpose @ y_train

# Делаем предсказание на тестовой выборке
y_pred_manual = X_test_manual @ w
mse_manual = np.mean((y_test - y_pred_manual) ** 2)

print(f"Ручной подсчет MSE на test: {mse_manual:.4f}")


# ВАРИАНТ 2: SCIKIT-LEARN
# Передаем чистые признаки, так как LinearRegression сама добавит intercept
model = LinearRegression() # fit_intercept=True - автоматически рассчитывать свободный член
model.fit(X_train_raw, y_train)

y_pred_sklearn = model.predict(X_test_raw)
mse_sklearn = mean_squared_error(y_test, y_pred_sklearn)

print(f"Sklearn подсчет MSE на test: {mse_sklearn:.4f}")




Ручной подсчет MSE на test: 21.5174
Sklearn подсчет MSE на test: 21.5174


5. **Псевдообратная.** Реализуйте `pinv(A)` через SVD (потом поймёте, как). Проверьте, что `A @ pinv(A) @ A ≈ A`.


In [18]:
# Подойдет любая матрица (прямоугольная, квадратная, вырожденная)
X = np.array([[1, 2], [3, 6], [5, 10]])

# 1. Прямое SVD разложение
U, sigma_values, Vt = np.linalg.svd(X)

# Матрица Sigma_plus всегда имеет транспонированный размер относительно X
sigma_plus = np.zeros((X.shape[1], X.shape[0]))

# Простой фиксированный порог для отсечения шума
tol = 1e-9

for i, val in enumerate(sigma_values):
    if val > tol:
        sigma_plus[i, i] = 1.0 / val

X_plus_manual = Vt.T @ sigma_plus @ U.T
print(f"Проверка утверждения прошла успешна? -> {np.allclose(X @ X_plus_manual @ X, X)}")

X_plus_numpy = np.linalg.pinv(X)
print(f"Numpy и Manual способы совпали? -> {np.allclose(X_plus_manual, X_plus_numpy)}")

Проверка утверждения прошла успешна? -> True
Numpy и Manual способы совпали? -> True


# Сингулярное разложение (SVD) и Псевдообратная матрица

## 1. Что такое Псевдообратная матрица?
**Псевдообратная матрица** (матрица Мура-Пенроуза, обозначается как $X^+$ или $X^\dagger$) — это математическое обобщение понятия обратной матрицы для неквадратных (прямоугольных) или вырожденных матриц. 

Она позволяет находить уникальное и наилучшее приближенное решение систем линейных уравнений, даже если точного решения не существует или матрица признаков является вырожденной.

### Почему она важна в линейной регрессии?
Классическая формула метода наименьших квадратов (МНК) требует вычисления обычной обратной матрицы:
$$w = (X^T X)^{-1} X^T Y$$

Однако матрица $X^T X$ может оказаться **вырожденной** (ее детерминант равен нулю, и взять обратную матрицу невозможно). Это происходит в двух случаях:
1. **Мультиколлинеарность**: два или более признака линейно зависимы (например, вес в кг и вес в граммах).
2. **Переразмеренность**: признаков (колонок) больше, чем объектов (строк) в данных ($k > n$).

Псевдообратная матрица $X^+$ полностью обходит эту проблему, заменяя собой всю конструкцию $(X^T X)^{-1} X^T$. Формула регрессии принимает вид:
$$w = X^+ Y$$

---

## 2. Математическая суть SVD
**SVD (Singular Value Decomposition)** — это теорема линейной алгебры, которая утверждает, что **любую** матрицу $X$ размера $n \times k$ можно разложить на произведение трех матриц специального вида:

$$X = U \Sigma V^T$$

Где компоненты разложения означают следующее:
* **$U$** (размер $n \times n$) — ортогональная матрица ($U^{-1} = U^T$). Ее столбцы называют *левыми сингулярными векторами* (они описывают геометрию строк исходной матрицы).
* **$V$** (размер $k \times k$) — ортогональная матрица ($V^{-1} = V^T$). Ее столбцы называют *правыми сингулярными векторами* (они описывают геометрию столбцов/признаков).
* **$\Sigma$** (размер $n \times k$) — диагональная матрица. На ее главной диагонали стоят **сингулярные числа** $\sigma_i$, расположенные по убыванию ($\sigma_1 \ge \sigma_2 \ge \dots \ge 0$). Они показывают «силу» или значимость каждого направления в данных.

---

## 3. Связь SVD с псевдообратной матрицей
Если для исходной матрицы разложение выглядит как $X = U \Sigma V^T$, то для нахождения псевдообратной матрицы $X^+$ формулу применяют в обратном порядке, инвертируя каждый компонент:

$$X^+ = V \Sigma^+ U^T$$

Ортогональные матрицы $U$ и $V$ инвертируются простым транспонированием. Вся магия происходит с диагональной матрицей $\Sigma$, которая превращается в $\Sigma^+$ по следующему алгоритму:
1. Каждое ненулевое сингулярное число на диагонали заменяется на обратное: $\sigma_i \to \frac{1}{\sigma_i}$.
2. Если сингулярное число $\sigma_i$ равно нулю (или бесконечно близко к нему из-за численной погрешности float), то вместо деления на ноль его **принудительно оставляют равным нулю**.
3. Полученная матрица транспонируется для соблюдения размерностей при умножении.

### Как это спасает вычисления?
Если в данных есть идеальная мультиколлинеарность, алгоритм на базе SVD не пытается делить на определитель, равный нулю. Он просто видит, что лишний зависимый признак порождает нулевое сингулярное число $\sigma_i = 0$, зануляет его в матрице $\Sigma^+$ и выдает стабильный вектор весов $w$.

---

## 4. Практический пример вычисления $X^+$ через SVD

Пусть дана вырожденная матрица признаков $X$ размера $2 \times 2$, где второй столбец линейно зависит от первого (идеальная мультиколлинеарность):

$$X = \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$$

Обычную обратную матрицу $X^{-1}$ найти нельзя, так как $\det(X) = 1 \cdot 4 - 2 \cdot 2 = 0$.

### Шаг 1. Нахождение сингулярного разложения $X = U \Sigma V^T$
Для этой матрицы компоненты SVD-разложения выглядят следующим образом:

* **Матрица $U$** (левые сингулярные векторы):
  $$U = \begin{pmatrix} \frac{1}{\sqrt{5}} & -\frac{2}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} \end{pmatrix}$$
* **Матрица $V$** (правые сингулярные векторы):
  $$V = \begin{pmatrix} \frac{1}{\sqrt{5}} & -\frac{2}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} \end{pmatrix} \implies V^T = \begin{pmatrix} \frac{1}{\sqrt{5}} & \frac{2}{\sqrt{5}} \\ -\frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} \end{pmatrix}$$
* **Матрица $\Sigma$** (сингулярные числа):
  $$\Sigma = \begin{pmatrix} 5 & 0 \\ 0 & 0 \end{pmatrix}$$
  *Второе сингулярное число равно $0$, так как ранг матрицы равен 1.*

### Шаг 2. Инвертирование матрицы $\Sigma \to \Sigma^+$
Применяем алгоритм Мура-Пенроуза: ненулевые элементы делим на единицу, нулевые — оставляем нулями.

$$\Sigma^+ = \begin{pmatrix} \frac{1}{5} & 0 \\ 0 & 0 \end{pmatrix}$$

### Шаг 3. Сборка псевдообратной матрицы $X^+ = V \Sigma^+ U^T$
Перемножаем матрицы в нужном порядке. Сначала найдем произведение $\Sigma^+ U^T$:

$$U^T = \begin{pmatrix} \frac{1}{\sqrt{5}} & \frac{2}{\sqrt{5}} \\ -\frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} \end{pmatrix}$$

$$\Sigma^+ U^T = \begin{pmatrix} \frac{1}{5} & 0 \\ 0 & 0 \end{pmatrix} \begin{pmatrix} \frac{1}{\sqrt{5}} & \frac{2}{\sqrt{5}} \\ -\frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} \end{pmatrix} = \begin{pmatrix} \frac{1}{5\sqrt{5}} & \frac{2}{5\sqrt{5}} \\ 0 & 0 \end{pmatrix}$$

Теперь умножаем $V$ на полученный результат:

$$X^+ = V (\Sigma^+ U^T) = \begin{pmatrix} \frac{1}{\sqrt{5}} & -\frac{2}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} \end{pmatrix} \begin{pmatrix} \frac{1}{5\sqrt{5}} & \frac{2}{5\sqrt{5}} \\ 0 & 0 \end{pmatrix}$$

Вычисляем элементы итоговой матрицы:
* Строка 1, столбец 1: $\frac{1}{\sqrt{5}} \cdot \frac{1}{5\sqrt{5}} + 0 = \frac{1}{25} = 0.04$
* Строка 1, столбец 2: $\frac{1}{\sqrt{5}} \cdot \frac{2}{5\sqrt{5}} + 0 = \frac{2}{25} = 0.08$
* Строка 2, столбец 1: $\frac{2}{\sqrt{5}} \cdot \frac{1}{5\sqrt{5}} + 0 = \frac{2}{25} = 0.08$
* Строка 2, столбец 2: $\frac{2}{\sqrt{5}} \cdot \frac{2}{5\sqrt{5}} + 0 = \frac{4}{25} = 0.16$

---

## ✅ Результат
Итоговая псевдообратная матрица $X^+$ успешно вычислена через SVD.

$$X^+ = \begin{pmatrix} 0.04 & 0.08 \\ 0.08 & 0.16 \end{pmatrix}$$


6. **Композиция преобразований.** Сделайте поворот на 30°, потом масштабирование в 2 раза по X. Найдите итоговую матрицу одним умножением. Проверьте, что результат совпадает.


In [19]:
# Исходная матрица точек (каждая строка — это [x, y])
X = np.array([
    [1.0, 1.0],
    [2.0, 3.0],
    [4.0, 1.0]
])

angle = np.pi / 6

# Матрица поворота
R = np.array([[np.cos(angle), np.sin(angle)], 
              [-np.sin(angle), np.cos(angle)]])

# Масштабирование по x
S = np.array([[2, 0], [0, 1]])

X_answer_one_step = X @ R @ S

X_rotated = X @ R
X_answer_two_step = X_rotated @ S

print(f"Результаты совпадают? -> {np.allclose(X_answer_one_step, 
                                               X_answer_two_step)}")





Результаты совпадают? -> True


7. **Проверка вырожденности.** Сгенерируйте 10 случайных матриц 5×5, добавьте к двум из них линейно зависимую строку. Найдите эти две через `matrix_rank`.


In [20]:
np.random.seed(42)

matrices = [np.random.randint(1, 100, (5, 5)).astype(float) for _ in range(10)]

degenerate_matrices = [np.random.randint(10) for _ in range(2)]

for i in degenerate_matrices:
    matrices[i][3] = 2 * matrices[i][0] + matrices[i][2]

check_matrix = []

for i, matrix in enumerate(matrices):
    rank = np.linalg.matrix_rank(matrix)

    if rank < 5:
        check_matrix.append(i)

print(np.allclose(degenerate_matrices, check_matrix))

True


8. **Свой solve.** Реализуйте решение `Ax = b` методом Гаусса (прямой и обратный ход). Сравните с `np.linalg.solve`.


In [ ]:
np.random.seed(42)

n = 5
A = np.random.randint(-100, 100, (n, n)).astype(float)
b = np.random.randint(-100, 100, (n, 1)).astype(float)
M = np.hstack([A, b]) # расширенная матрица A|b
# print(M)
# Forward step
for i in range(n):
    # так как срез это новый массив, индекс начинается с нуля,
    # поэтому не забываем учесть смещение + i
    row_idx = np.abs(M[i:, i]).argmax() + i
    M[[i, row_idx]] = M[[row_idx, i]]

    for j in range(i + 1, n):
        factor = M[j, i] / M[i, i]
        M[j] = M[j] - factor * M[i]
    # print(np.round(M, 1))
    # break

# Reverse step
x = np.zeros(n)
x[n - 1] = M[n - 1, n] / M[n - 1, n - 1]

for i in range(n - 2, -1, -1):
    # используем скалярное произведение двух векторов
    x[i] = (M[i, n] - M[i, i + 1 : n] @ x[i + 1 : n]) / M[i, i]

print(f"Ответ СЛАУ: {x.round(3)}")

# нужно использовать flatten(), так как x одномерный, а b двумерный
# flatten() превращает ЛЮБОЙ многомерный массив в одномерный
print(np.allclose(np.linalg.solve(A, b).flatten(), x))


[[  2.  79.  -8. -86.   6.  87.]
 [-29.  88. -80.   2.  21. -80.]
 [-26. -13.  16.  -1.   3.  60.]
 [ 51.  30.  49. -48. -99. -43.]
 [-13.  57. -63.  29.  91. -79.]]
[[  51.    30.    49.   -48.   -99.   -43. ]
 [   0.   105.1  -52.1  -25.3  -35.3 -104.5]
 [   0.     2.3   41.   -25.5  -47.5   38.1]
 [   0.    77.8   -9.9  -84.1    9.9   88.7]
 [   0.    64.6  -50.5   16.8   65.8  -90. ]]
Ответ СЛАУ: [-1.848 -2.446 -1.411 -1.215 -1.368]
False


---
### 1. Умножаете матрицы руками на бумаге для $2 \times 2$

Умножение матриц выполняется по правилу **«строка на столбец»**. Чтобы найти элемент на пересечении $i$-й строки и $j$-го столбца результирующей матрицы, нужно скалярно перемножить $i$-ю строку первой матрицы на $j$-го столбец второй матрицы.

Формула в общем виде выглядит так:

$$ \begin{pmatrix} a & b \\ c & d \end{pmatrix} \cdot \begin{pmatrix} e & f \\ g & h \end{pmatrix} = \begin{pmatrix} ae + bg & af + bh \\ ce + dg & cf + dh \end{pmatrix} $$

**Зачем это нужно:** Это базовое арифметическое действие в линейной алгебре. Без его понимания невозможно разобраться в том, как преобразуются размерности тензоров при прохождении через полносвязные (Dense) или сверточные (CNN) слои нейросети.

---

### 2. Можете объяснить, почему $AB \neq BA$

В отличие от умножения обычных чисел, умножение матриц **некоммутативно**. Результат операции напрямую зависит от порядка множителей по двум фундаментальным причинам:

* **Размерностная причина:** Матрицы можно умножать только тогда, когда количество столбцов первой матрицы совпадает с количеством строк второй. Если матрица $A$ имеет размер $3 \times 2$, а матрица $B$ — размер $2 \times 5$, то произведение $AB$ существует и имеет размер $3 \times 5$. Однако произведение $BA$ (попытка умножить матрицу размера $2 \times 5$ на матрицу размера $3 \times 2$) вычислить физически невозможно, так как внутренние размерности ($5$ и $3$) не совпадают.
* **Геометрическая причина:** Матрица — это линейный оператор, который трансформирует пространство (поворачивает, растягивает, отражает). Последовательность этих действий критически важна. Например, если $A$ — это поворот пространства на $90^\circ$, а $B$ — сдвиг вдоль оси $X$, то в случае $BA$ мы сначала поворачиваем объект, а затем сдвигаем. В случае $AB$ — сначала сдвигаем, а потом поворачиваем вокруг нового центра координат. Итоговое положение объекта в этих сценариях будет абсолютно разным.

---

### 3. Понимаете, что слой нейросети $Wx + b$ — это аффинное преобразование

Полносвязный слой нейросети до применения нелинейной функции активации выполняет операцию $Wx + b$, где $x$ — вектор входа, $W$ — матрица весов, $b$ — вектор смещения (bias).

**Аффинное преобразование** — это комбинация линейного преобразования и параллельного переноса (сдвига):

* **Линейная часть ($Wx$):** Матрица $W$ сжимает, растягивает или вращает координатную сетку. При линейном преобразовании точка начала координат $(0, 0)$ обязана оставаться на месте. Если на вход подать нулевой вектор $x = 0$, то $W \cdot 0 = 0$. Без смещения разделяющая гиперплоскость нейросети всегда будет намертво привязана к центру координат.
* **Сдвиг ($+ b$):** Вектор $b$ смещает всю трансформированную координатную сетку в пространстве на определенное расстояние. Это позволяет разделяющей линии или плоскости проходить через любые координаты, что жизненно необходимо для точного разделения классов, которые не сгруппированы вокруг математического нуля.

---

### 4. Решаете линейную регрессию через нормальные уравнения

Вместо итеративного поиска весов с помощью градиентного спуска, аналитическое решение задачи линейной регрессии по методу наименьших квадратов (МНК) можно найти за один шаг с помощью **нормального уравнения**:

$$ w = (X^T X)^{-1} X^T y $$

* $X$ — матрица признаков (размерности $m \times n$, где $m$ — число примеров, $n$ — число признаков).
* $y$ — вектор-столбец правильных ответов.
* $w$ — искомый вектор оптимальных весов модели.
* $X^T$ — транспонированная матрица признаков.
* $(X^T X)^{-1}$ — обратная матрица для скалярного произведения признаков.

Этот метод мгновенно находит глобальный минимум функции потерь (MSE) без необходимости настраивать скорость обучения (learning rate) или делать тысячи итераций. Однако он применим только для небольших датасетов, так как вычисление обратной матрицы для больших размерностей требует слишком много вычислительных ресурсов.

---

### 5. Знаете, почему `solve` лучше `inv`

При решении системы линейных уравнений вида $Ax = b$ в коде (используя `numpy.linalg`, `scipy` или `PyTorch`) у вас есть два математически эквивалентных пути:
1. Вычислить обратную матрицу явно и умножить на вектор: `x = inv(A) @ b` (что соответствует формуле $x = A^{-1}b$).
2. Использовать специализированный решатель: `x = solve(A, b)`.

Функция `solve` является стандартом для вычислений по следующим причинам:

* **Вычислительная точность:** Компьютеры работают с числами с плавающей точкой ограниченной разрядности (`float32` / `float64`), что неизбежно приводит к ошибкам округления. Явное взятие обратной матрицы `inv(A)` требует огромного количества операций деления. Если матрица $A$ близка к вырожденной (плохо обусловлена), эти ошибки растут лавинообразно и полностью искажают результат. Функция `solve` использует численно устойчивые алгоритмы (например, LU-разложение с выбором главного элемента), минимизирующие погрешность.
* **Вычислительная сложность и скорость:** Чтобы найти `inv(A)`, алгоритму нужно совершить порядка $N^3$ операций и полностью построить матрицу $A^{-1}$ в памяти. Функция `solve` находит конкретный вектор $x$ напрямую через прямую и обратную подстановку в треугольных матрицах, вообще не тратя ресурсы процессора и памяти на генерацию промежуточной обратной матрицы. Это экономит до 3 раз больше элементарных операций.
